routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//Route::get('/home', 'HomeController@index')->name('home')->middleware('chkIfAdmin');

// Route::get('/admin', ['middleware' => 'chk', function () {

//     return view('admin.posts');
// }]);

// Route::get('/', 'PagesController@index', function () {
//     return view('/pages');
// });

Auth::routes(['verify' => true]);

Route::get('/home', 'PagesController@index')->name('home');

//ADMIN CONTROLLER
Route::prefix('admin')->middleware(['auth', 'chkIfAdmin', 'chkIfActive'])->group( function () {
    Route::get('test', 'AdminController@test')->name('admin.test');
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('posts/posts', 'AdminController@posts')->name('admin.posts');
    Route::get('posts/allposts', 'AdminController@allposts')->name('admin.allposts');
    Route::get('posts/activeposts', 'AdminController@activeposts')->name('admin.activeposts');
    Route::get('posts/pendingposts', 'AdminController@pendingposts')->name('admin.pendingposts');
    Route::get('rejectedposts', 'AdminController@rejectedposts')->name('admin.rejectedposts');
    Route::get('posts/edit/{post}', 'AdminController@editpost')->name('admin.editpost');
    Route::put('posts/edit/{post}', 'AdminController@updatepost')->name('updatepost');
    
    // USER CONTROLLER
    Route::get('users/users', 'AdminController@users')->name('admin.users');
    Route::get('users/{user}', 'AdminController@edit')->name('admin.edituser');
    Route::put('users/{id}/update', 'AdminController@update')->name('admin.updateuser');

    // CATEGORY CONTROLLER
    Route::get('category', 'AdminController@cretecategory')->name('admin.newcategory');
});

// PROFILE CONTROLLER
Route::prefix('profile')->middleware(['auth', 'verified', 'chkIfActive'])->group( function () {
    Route::get('{user}', 'ProfileController@profile')->name('profile.profile');
    Route::put('{user}', 'ProfileController@update')->name('profile.update');
}); 

// POSTS RESOURCE CONTROLLER
Route::resource('posts', 'PostController');

// PAGES CONTROLLER
Route::get('/', 'PagesController@index')->name('pages.index');
Route::get('/inactive', 'PagesController@inactive')->name('pages.inactive');
Route::get('/{id}', 'PagesController@show')->name('pages.show');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'body', 'user_id'];

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function categories() {
        return $this->belongsToMany('App\Category', 'category_post'); // second argument is pivot table name
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\User;
use App\Category;
use Auth;

class PostController extends Controller
{
   
    public function __construct() {

        $this->middleware(['auth', 'verified', 'chkIfActive'])->except(['index', 'show']);

     }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::where('user_id', auth()->id());
        
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $categories)
    {
        $categories = Category::orderBy('created_at', 'desc')->get();

        return view('posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'title'=>['required', 'string'],
            'body'=>['required'],
            'image' => ['required', 'image', 'max:2048'],
            'categories' => ['required', 'exists:categories,id']
        ]);

        $post = new Post;
        $post->title = $request->input('title');
        $post->body = ($request->input('body')); // htmlentities to escape illegal characters

        $post->user_id = Auth::user()->id;

        if ($request->hasFile('image')) {
            $imgName = date('Y-m-d'). "_" . 
            $request->file('image')->getClientOriginalName();
            $post->image = $imgName;
        }

        if ($post->save()) {
            $post->categories()->attach($request->input('categories'));
            $request->image->move(public_path('images'), $imgName);
            
            return redirect()->route('profile.profile', $post->user_id)->with('success', 'Post Successfully Created!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post, User $user)
    {
        // if (auth()->id() != $post->user_id) {
        //     abort(404);
        // }
 
        if (auth()->id() == $post->user_id) {
            return view('posts.edit', compact('post'));
        } else {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {

        $request->validate([
            'title'=> ['required'],
            'body'=> ['required'],
            'image'
        ]);

        if ($request->hasFile('image')) {
            $imgName = date('Y-m-d'). "_" . 
            $request->file('image')->getClientOriginalName();
            $post->image = $imgName;
            $request->image->move(public_path('images'), $imgName);
        }

        $post->update(request([
            'title',
            'body',
            'image'
        ]));

        return redirect()->route('profile.profile', ['user_id' => $post->user_id])->with('success', 'Post with title ' . $post->title . ' has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (auth()->id() != $post->user_id) {
            abort(404);
        }

        $post->delete();

        return redirect()->route('profile.profile', $post->user_id)->with('danger', 'Post with title ' . $post->title . ' has been deleted.');
        
    }
    
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

<head id="section-header-create">

</head>

<section id="section-create-1">

<div class="container">
    <form method="POST" action="{{route('posts.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}
            <div class="form-group">
            <label for="title">Post Title</label>
            <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" id="title" name="title" aria-describedby="title-Help" placeholder="Post title..." value="{{old('title')}}">
            <small id="titleHelp" class="form-text text-muted">Title of the post.</small>
                @if ($errors->has('title'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
                @endif
            </div>
            <div class="form-group">
                <label for="body">Post Body</label>
            <textarea class="form-control my-editor {{ $errors->has('body') ? 'is-invalid' : '' }}" id="body" name="body" rows="3">{{old('body')}}</textarea>
                <small id="titleHelp" class="form-text text-muted">Post content.</small>
                @if ($errors->has('body'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('body') }}</strong>
                </span>
                @endif
            </div>
            <div class="form-group">
                <input type="file" name="image" id="image"/>
            </div>
            {{-- <div class="custom-control custom-checkbox custom-control-inline">
                @if (count($categories))
                    @foreach($categories as $category)
                    <div class="custom-control custom-checkbox custom-control-inline">
                        <input type="checkbox" name="category[]" class="custom-control-input text-lowercase row_check
                                {{ $errors->has('category') ? 'is-invalid' : '' }}"
                                id="{{ "category-" . utf8_decode($category->name) }}" value="{{ $category->id }}" 
                                {{ $loop->first ? 'checked' : '' }}
                                {{ in_array($category->id, old('category', [])) ? 'checked' : '' }}>
                        <label class="custom-control-label text-lowercase" for="{{ "category-". utf8_decode($category->name) }}">{{
                                utf8_decode($category->name) }}</label>
                    </div>
                    @endforeach
                @else
                    <p>
                        There is no category at the moment.
                    </p>
                @endif
            </div> --}}
            <div class="form-group row">
                    {{-- POST TAGS --}}
                    <div class="col-lg-12">
                        <strong class="text-muted mb-3 mt-4 d-block">Tags:</strong>
    
                        @if( !count($categories) )
                        <h6>No categories found.</h6>
                        @else
                        <div class="custom-control custom-checkbox custom-control-inline">
                            <input type="checkbox" id="select_all" class="custom-control-input text-lowercase">
                            <label class="custom-control-label text-uppercase" for="select_all"><strong>select all</strong></label>
                        </div>
                        @foreach( $categories as $category )
                        <div class="custom-control custom-checkbox custom-control-inline">
                            <input type="checkbox" name="categories[]" class="custom-control-input text-lowercase row_check
                                {{ $errors->has('category') ? 'is-invalid' : '' }}" 
                                id="{{ "category-" . utf8_decode($category->name) }}" value="{{ $category->id }}" 
                                {{ $loop->first ? 'checked' : '' }}
                                {{ in_array($category->id, old('category', [])) ? 'checked' : '' }}>
                            <label class="custom-control-label text-lowercase" for="{{ "category-". utf8_decode($category->name) }}">
                            {{ utf8_decode($category->name) }}</label>
                        </div>
                        @endforeach

                        @if( $errors->has('categories') )
                        <small id="{{ strtolower(utf8_decode($category->name)) }}" class="form-text text-danger">
                            <strong>{{ $errors->first('categories') }}</strong>
                        </small>
                        @endif

                        @endif
                    </div>
                </div>
            <div class="form-group">
            <a class="btn btn-danger" href="{{URL::previous()}}">Cancel</a>
                <button type="submit" class="btn btn-primary">
                        {{ __('Submit') }}
                </button>
            </div>
    </form>
</div>
</section>



<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
{{-- <textarea name="content" class="form-control my-editor">{!! old('content', $content) !!}</textarea> --}}
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | forecolor backcolor",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);

    $('#select_all').on('click', (e) => {
            $('.row_check').prop('checked', $(e.target).prop('checked'));
        })

        $('.row_check').on('click', () => {
            if ($('.row_check:checked').length == $('.row_check').length) {
                $('#select_all').prop('checked', true)
            } else {
                $('#select_all').prop('checked', false)
            }
    })
</script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<header id="section-header-edit">

</header>

<section id="section-edit-1">
    <div class="container">
        <div class="container">
            <form method="POST" action="/posts/{{$post->id}}" enctype="multipart/form-data">
                {{method_field('PUT')}}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="title">Post Title</label>
                    <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" id="title"
                        name="title" aria-describedby="title-Help" placeholder="Post title..." value="{{$post->title}}">
                    <small id="titleHelp" class="form-text text-muted">Title of the post.</small>
                    @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="body">Post Body</label>
                    <textarea class="form-control my-editor {{ $errors->has('body') ? 'is-invalid' : '' }}" id="body" name="body"
                        rows="3">{!! html_entity_decode($post->body) !!}</textarea>
                    <small id="titleHelp" class="form-text text-muted">Post content.</small>
                    @if ($errors->has('body'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('body') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group">
                    <img src="{{asset('images/' . $post->image)}}" alt="">
                    <input type="file" name="image" id="image" />
                </div>
                <a class="btn btn-danger" href="{{URL::previous()}}">Cancel</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>



<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
{{-- <textarea name="content" class="form-control my-editor">{!! old('content', $content) !!}</textarea> --}}
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | forecolor backcolor",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('title', 'Profile')

@section('content')

<header id="section-header-home">

</header>

<section id="section-home-1">

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="row">
                    <div class="col d-flex justify-content-center">
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                @if(count($posts) > 0)
                <div class="row">
                    @foreach($posts as $post)
                    <div class="col-6">
                        <div class="card" style="width:;">
                            <img class="card-img-top" src="{{asset('images/' . $post->image)}}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title"><a href="posts/{{$post->id}}">{{$post->title}}</a></h5>
                                <p class="card-text">{{$post->body}}</p>
                                <small class="card-text">By: {{$post->user->name}}</small>
                                <br>
                                <small class="card-text">Email: {{$post->user->email}}</small>
                                <p><small class="card-text">Created On: {{$post->created_at}}</small></p>
                                <a href="posts/{{$post->id}}" class="btn btn-primary">View Post</a>
                                @auth
                                <a href="/posts/{{$post->id}}/edit" class="btn btn-danger">Edit</a>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                    Delete
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Do you really want to delete
                                                    this item?</h5>
                                            </div>
                                            <div class="modal-footer">
                                            <form method="POST" action="posts/{{$post->id}}">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endauth
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                ...
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="button" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    @endforeach
                    {{$posts->links()}}
                </div>
                @else
            </div>    
            <h3>There is no post at the moment.</h3>
            @endif
        </div>
    </div>

</section>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<header id="section-header-update">

</header>
    
<section id="section-update-1">
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <div class="card" style="width:50rem;">
                    <img class="card-img-top" src="{{asset('images/' . $post->image)}}" alt="Card image cap">
                    <div class="card-body">
                        <div>
                            @foreach( $post->categories as $pc )
                                <strong>
                                    {{ $pc->name }}
                                    {{ !$loop->last ? ',' : '' }}
                                </strong>
                            @endforeach
                        </div>
                        <h5 class="card-title">{{$post->title}}</h5>
                        <p class="card-text">{!! html_entity_decode($post->body) !!}</p>
                        <small class="card-text">By: {{$post->user->name}}</small>
                        <p><small class="card-text">Created On: {{$post->created_at}}</small></p>
                        <a href="{{URL::previous()}}" class="btn btn-primary">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection