routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//Route::get('/home', 'HomeController@index')->name('home')->middleware('chkIfAdmin');

// Route::get('/admin', ['middleware' => 'chk', function () {

//     return view('admin.posts');
// }]);

// Route::get('/', 'PagesController@index', function () {
//     return view('/pages');
// });

Auth::routes(['verify' => true]);

Route::get('/home', 'PagesController@index')->name('home');

//ADMIN CONTROLLER
Route::prefix('admin')->middleware(['auth', 'chkIfAdmin', 'chkIfActive'])->group( function () {
    Route::get('test', 'AdminController@test')->name('admin.test');
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('posts/posts', 'AdminController@posts')->name('admin.posts');
    Route::get('posts/allposts', 'AdminController@allposts')->name('admin.allposts');
    Route::get('posts/activeposts', 'AdminController@activeposts')->name('admin.activeposts');
    Route::get('posts/pendingposts', 'AdminController@pendingposts')->name('admin.pendingposts');
    Route::get('rejectedposts', 'AdminController@rejectedposts')->name('admin.rejectedposts');
    Route::get('posts/edit/{post}', 'AdminController@editpost')->name('admin.editpost');
    Route::put('posts/edit/{post}', 'AdminController@updatepost')->name('updatepost');
    
    // USER CONTROLLER
    Route::get('users/users', 'AdminController@users')->name('admin.users');
    Route::get('users/{user}', 'AdminController@edit')->name('admin.edituser');
    Route::put('users/{id}/update', 'AdminController@update')->name('admin.updateuser');

    // CATEGORY CONTROLLER
    Route::get('category', 'AdminController@cretecategory')->name('admin.newcategory');
});

// PROFILE CONTROLLER
Route::prefix('profile')->middleware(['auth', 'verified', 'chkIfActive'])->group( function () {
    Route::get('{user}', 'ProfileController@profile')->name('profile.profile');
    Route::put('{user}', 'ProfileController@update')->name('profile.update');
}); 

// POSTS RESOURCE CONTROLLER
Route::resource('posts', 'PostController');

// PAGES CONTROLLER
Route::get('/', 'PagesController@index')->name('pages.index');
Route::get('/inactive', 'PagesController@inactive')->name('pages.inactive');
Route::get('/{id}', 'PagesController@show')->name('pages.show');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Allan | @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    
    @yield('custom-styles')
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">

</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item">
                        <a class="nav-link active" href="{{URL('/')}}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" href="{{route('posts.create')}}">Create Post</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" href="{{route('profile.profile', Auth::user()->id)}}">Profile</a>
                        </li>
                        <li class="nav justify-content-end">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @include('layouts.messages')
            @yield('content')
        </main>
    </div>
        @yield('footer')
</body>

</html>

resources/views/layouts/footer.blade.php
<footer id="footer">
    <div class="container-fluid">
        <div class="footer-content text-center">
            <img src="{{asset('/images/footer/kuya.jpg')}}" alt="Logo">
            <br>
            <b>This is a sample laravel blog project.</b>
        </div>
    </div>
</footer>

resources/views/layouts/messages.blade.php
{{-- @if(count($errors) > 0)
    @foreach($errors->all() as $error)
    <div class="container">
        <div class="alert alert-danger">
            {{$error}}
        </div>
    </div>     
    @endforeach
@endif --}}


@if(session('success'))
    <div class="container-fluid">
        <div class="alert alert-success">
            {{session('success')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
@endif

@if(session('error'))
<div class="container-fluid">
    <div class="alert alert-danger">
        {{session('error')}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
@endif